use gtk4::{Box as GtkBox, Button, CheckButton, ComboBoxText, Entry, Label, TextView};
#[derive(Clone)]
pub struct EntryWidgets {
    pub type_combo: ComboBoxText,
    pub name_entry: Entry,
    pub generic_name_entry: Entry,
    pub comment_entry: Entry,
    pub exec_entry: Entry,
    pub icon_entry: Entry,
    pub terminal_check: CheckButton,
    pub nodisplay_check: CheckButton,
    pub startup_check: CheckButton,
    pub categories_entry: Entry,
    pub mimetype_entry: Entry,
    pub keywords_entry: Entry,
    pub onlyshowin_entry: Entry,
    pub notshowin_entry: Entry,
    pub tryexec_entry: Entry,
    pub path_entry: Entry,
    pub url_entry: Entry,
    pub actions_entry: Entry,
    pub localized_name: TextView,
    pub localized_gname: TextView,
    pub localized_comment: TextView,
    pub extra_kv: TextView,
    pub exec_lbl: Label,
    pub exec_app_box: GtkBox,
    pub exec_link_box: GtkBox,
    pub exec_btn: Button,
    pub url_btn: Button,
}
impl EntryWidgets {
    pub fn clone_all(&self) -> Self {
        Self {
            type_combo: self.type_combo.clone(),
            name_entry: self.name_entry.clone(),
            generic_name_entry: self.generic_name_entry.clone(),
            comment_entry: self.comment_entry.clone(),
            exec_entry: self.exec_entry.clone(),
            icon_entry: self.icon_entry.clone(),
            terminal_check: self.terminal_check.clone(),
            nodisplay_check: self.nodisplay_check.clone(),
            startup_check: self.startup_check.clone(),
            categories_entry: self.categories_entry.clone(),
            mimetype_entry: self.mimetype_entry.clone(),
            keywords_entry: self.keywords_entry.clone(),
            onlyshowin_entry: self.onlyshowin_entry.clone(),
            notshowin_entry: self.notshowin_entry.clone(),
            tryexec_entry: self.tryexec_entry.clone(),
            path_entry: self.path_entry.clone(),
            url_entry: self.url_entry.clone(),
            actions_entry: self.actions_entry.clone(),
            localized_name: self.localized_name.clone(),
            localized_gname: self.localized_gname.clone(),
            localized_comment: self.localized_comment.clone(),
            extra_kv: self.extra_kv.clone(),
            exec_lbl: self.exec_lbl.clone(),
            exec_app_box: self.exec_app_box.clone(),
            exec_link_box: self.exec_link_box.clone(),
            exec_btn: self.exec_btn.clone(),
            url_btn: self.url_btn.clone(),
        }
    }
}
